# src/main/resources/application.yml

sftp:
  host: sftp.example.com
  port: 22
  username: sftpuser
  privateKey: /path/to/private/key
  remoteDir: /remote/dir
  localDir: /local/dir

pgp:
  privateKey: /path/to/pgp/privatekey.asc
  publicKey: /path/to/pgp/publickey.asc
  passphrase: your_passphrase
